### ISSUE TITLE
Show Stopper: Latest version 1.3.0 breaks on python 2.6

### ISSUE THREAD

**Issue by chfw** [eea/odfpy#17]
Hi all,

The new release breaks with python 2.6. By the way, is odfpy dropping the support for 2.6?

Cheers.

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName

    addr.filename, addr.module)

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/home/travis/build/chfw/pyexcel-ods/pyexcel_ods/__init__.py", line 38, in <module>

    import odf.opendocument

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/odf/opendocument.py", line 38, in <module>

    import manifest

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/odf/manifest.py", line 27, in <module>

    from element import Element

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/odf/element.py", line 33, in <module>

    if sys.version_info.major == 3:

AttributeError: 'tuple' object has no attribute 'major'

More details here: https://travis-ci.org/chfw/pyexcel-ods/jobs/64445131

**Comment by sorenroug** [comment]
We have not intentionally dropped support for Python 2.6. I accepted some patches to make it work on Python 3. Those patches used sys.version_info.major, which is only available from Python 2.7. I've changed those occurrences to sys.version_info[0] and checked it into GitHub, but I haven't had time to make a new release.

**Comment by chfw** [comment]
Has seen 1.3.1 released. Hence, this issue is gone
