### ISSUE TITLE
Image Attachment fails unicode test in Python 2.7

### ISSUE THREAD

**Issue by sicada** [eea/odfpy#26]
I noticed that after upgrading to the latest version of odfpy, that attempting to attach images was causing an AssertionError in python 2.7. The issue was that the incoming image path was a python str, but the code in opendocument.py was expecting unicode. In Python 2.7 unicode != str and thus the assert throws an error. 

==== Relevant Tracebacks ====
```
Traceback (most recent call last):
  File "docs/odf_main.py", line 155, in _create_cover_page_header_footer
    LogoHref  = self.odfDoc.addPicture(image_path)
  File "venv/local/lib/python2.7/site-packages/odf/opendocument.py", line 438, in addPicture
    assert(type(mediatype)==type(u""))
AssertionError
```

```
File "../venv/local/lib/python2.7/site-packages/odf/opendocument.py", line 572, in save
    assert(type(outputfile)==type(u"") or 'wb' in repr(outputfile) or 'BufferedWriter' in repr(outputfile)  or 'BytesIO' in repr(outputfile))
AssertionError
```

==== Patch which fixed all problems for me ====

```
--- opendocument.py.orig	2015-11-04 16:14:44.833193579 -0600
+++ opendocument.py	2015-11-04 16:17:54.570278640 -0600
@@ -426,6 +426,12 @@
                 except: ext=u''
             else:
                 ext = mimetypes.guess_extension(mediatype)
+
+            if type(filename) == type(""):
+                filename  = unicode(filename)
+            if type(mediatype) == type(""):
+                mediatype = unicode(mediatype)
+
             manifestfn = u"Pictures/%0.0f%s" % ((time.time()*10000000000), ext)
             self.Pictures[manifestfn] = (IS_FILENAME, filename, mediatype)
             content=b""  # this value is only use by the assert further
@@ -459,6 +465,12 @@
             except ValueError: ext=u''
         else:
             ext = mimetypes.guess_extension(mediatype)
+
+        if type(filename) == type(""):
+            filename  = unicode(filename)
+        if type(mediatype) == type(""):
+            mediatype = unicode(mediatype)
+
         manifestfn = u"Pictures/%0.0f%s" % ((time.time()*10000000000), ext)
         self.Pictures[manifestfn] = (IS_FILENAME, filename, mediatype)
 
@@ -569,6 +581,10 @@
         the ZIP content.
         @param addsuffix boolean: whether to add a suffix or not; defaults to False
         """
+        
+        if type(outputfile) == type(""):
+            outputfile = unicode(outputfile)
+        
         assert(type(outputfile)==type(u"") or 'wb' in repr(outputfile) or 'BufferedWriter' in repr(outputfile)  or 'BytesIO' in repr(outputfile))
         assert(type(addsuffix)==type(True))

```

**Comment by csawyerYumaed** [comment]
This is annoying.
