### ISSUE TITLE
latest odfpy does not work under python 3

### ISSUE THREAD

**Issue by chfw** [eea/odfpy#34]
Hi all

Here is an [overview](https://travis-ci.org/pyexcel/pyexcel-ods) and odfpy failed to start across python 3 versions. I think it is related to relative imports:

    ======================================================================
    ERROR: Failure: ImportError (No module named 'namespaces')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 180, in load_module
        return load_source(name, filename, file)
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 119, in load_source
        _LoadSourceCompatibility(name, pathname, file).load_module(name)
      File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
      File "<frozen importlib._bootstrap>", line 1022, in load_module
      File "<frozen importlib._bootstrap>", line 1003, in load_module
      File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
      File "<frozen importlib._bootstrap>", line 868, in _load_module
      File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
      File "/home/travis/build/pyexcel/pyexcel-ods/tests/test_bug_fixes.py", line 4, in <module>
        from pyexcel_ods import get_data, save_data
      File "/home/travis/build/pyexcel/pyexcel-ods/pyexcel_ods/__init__.py", line 26, in <module>
        from odf.table import TableRow, TableCell, Table
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/odf/table.py", line 21, in <module>
        from namespaces import TABLENS
    ImportError: No module named 'namespaces'

**Comment by aq1** [comment]
Oh my. That's interesting. I've been trying to package my program with pyinstaller and I received the same error when I try to run the build. What I did was to edit source of this library a little - replace 
`from namespaces import TABLENS`
with
`from odf.namespaces import TABLENS`
After that the build worked.
Of course you have to do it with every import in every file. But there is not so much files. It takes 5 minutes.
Also, you can find source of the library with this command:
```
import odf
print(odf.__file__)
```

**Comment by chfw** [comment]
Can you submit a PR instead?

**Comment by aq1** [comment]
Yeah. I was thinking about It.
I will do it a little bit later when I get to home.

**Comment by chfw** [comment]
Your PR works perfectly with [python 3.3, 3.4, 3.5](https://travis-ci.org/pyexcel/pyexcel-ods/builds/136385935). Here is [how it was before](https://travis-ci.org/pyexcel/pyexcel-ods/builds/136360409)

**Comment by aq1** [comment]
Glad to hear it.
Also, you know about my problem: I just replaced odfpy in my requirements.txt file and now I don't have to wait for PR to be accepted. But this is temporary workaround of course.
https://github.com/aq1/Hospital-Helper-2/commit/47f72dd8c00b6e1418bf8d3db9886872d7e693d4

**Comment by chfw** [comment]
Great that you found a way to use your own fork in your project. 

To all, I indeed need PR https://github.com/eea/odfpy/pull/36 to go into the next release to address https://github.com/pyexcel/pyexcel-ods/issues/8

**Comment by chfw** [comment]
Waiting for next pypi release that contains #36
