### ISSUE TITLE
Test failure in test_xmlgenerator_wo_ns (testxmlgen.TestXMLGenerator)

### ISSUE THREAD

**Issue by Nodd** [eea/odfpy#8]
One test seems broken:

```
$ python2.7 -m unittest discover tests/
................................................................/Object 1
..........E..........
======================================================================
ERROR: test_xmlgenerator_wo_ns (testxmlgen.TestXMLGenerator)
Test that the missing xml namespace is understood by XMLGenerator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joseph/prog/odfpy.git/tests/testxmlgen.py", line 73, in test_xmlgenerator_wo_ns
    parser.feed(testcontent)
  File "/usr/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 353, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/usr/lib/python2.7/site-packages/_xmlplus/sax/saxutils.py", line 281, in startElementNS
    elif self._current_context[name[0]] is None:
KeyError: u'http://www.w3.org/XML/1998/namespace'

----------------------------------------------------------------------
Ran 85 tests in 1.218s

FAILED (errors=1)
```

**Comment by mcepl** [comment]
It seems to me that odfpy uses pytest instead of just unittest, so the right incantation for running the testsuite is:
```sh
$ PYTHONPATH=build/lib pytest -v
```
